### ISSUE TITLE
Using with sphinx-book-theme

### ISSUE THREAD

**Issue by zerothi** [pradyunsg/sphinx-inline-tabs#39]
When using these tabs with the book-theme I get a weird empty region:
Note the light gray bounding box line around the tabbed region.

![sphinx-book-theme-inline-tabs](https://github.com/pradyunsg/sphinx-inline-tabs/assets/4789793/c88a1428-d63c-4a99-973d-9fcd7ef4a149)

This looks a bit weird. This does not occur in the rtfd docs theme where the background gets correctly filled.

I have this custom css:
```css
/*The parent container of tabs*/
.tab-set {
  border: 1px solid #ccc
}

/*Individual box of each tab*/
.tab-set > label {
  margin-bottom: 0
}

/*Container appearing below the tabs, with the contents of the active tab*/
.tab-content {
  background-color: aliceblue;
  padding: 20px
}

/*Initial paragraph of the content. By default there's a top margin 
 but we already specify a padding of 20 px for the content no matter what the
 first child is.*/
.tab-content > p:first-child {
  margin-top: 0
}
```

I much prefer the look of these minimal tabs compared to the others around. :)

Thanks for the package!
